version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
      #network_mode: host
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - "1883:1883"
    restart: always
